### ISSUE TITLE
GitHub test workflow is currently broken

### ISSUE THREAD

**Issue by jsf9k** [cisagov/ansible-role-kali#45]
# 🐛 Bug Report #

It appears that the `chromium` package is no longer available on Kali Linux.  This is breaking the installation of [Aquatone](https://github.com/michenriksen/aquatone).

See [this APB run](https://github.com/cisagov/ansible-role-kali/runs/1552789514?check_suite_focus=true).

## To Reproduce ##

Just re-run the APB run mentioned in the previous section.

## Expected behavior ##

The APB run should complete successfully.

## Any helpful log output ##

```
  TASK [ansible-role-kali : Install dependencies for aquatone] *******************
  fatal: [kali]: FAILED! => {"changed": false, "msg": "No package matching 'chromium' is available"}
```

**Comment by jsf9k** [comment]
It appears that [there are some problems](https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=chromium;dist=unstable) with Chromium on Debian Testing (currently Bullseye AKA 11, on which Kali Linux is based); hence, [it has been removed for now](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=973848).  This is one of the many dangers of basing a distribution on Debian Testing - packages can disappear at any time and for any length of time.

The simplest solution here is to remove Aquatone from this Ansible role until the package reappears in Debian Bullseye and Kali.

**Comment by jsf9k** [comment]
Another option is to install Google Chrome and hope for the best, although [the Aquatone README](https://github.com/michenriksen/aquatone#installation) states that there have been problems using Chrome headless.

**Comment by jsf9k** [comment]
@justinforbes - Is Aquatone something you guys use a lot, often, rarely?  I'm trying to get a gauge as to how much work I should put into this right now.  The options are:
* Remove Aquatone and wait for Chromium to be re-added to Debian Bullseye/Kali (no work)
* Install Google Chrome on Kali and hope that Aquatone works with it despite [this warning](https://github.com/michenriksen/aquatone#installation) (shouldn't be that much work - [I _think_ I can pull in a PPA](https://computingforgeeks.com/install-google-chrome-browser-on-kali-linux/))
* Figure out a way to get Chromium installed on Kali _now_ (more work - I don't know how to do this right now)

What's your thought?

**Comment by justinforbes** [comment]
We use it on every assessment, I think it works with Google chrome so that's probably the best way forward.

**Comment by jsf9k** [comment]
> We use it on every assessment, I think it works with Google chrome so that's probably the best way forward.

@justinforbes, if you find later that Aquatone _doesn't_ work with Google Chrome please create an issue.

**Comment by mcdonnnj** [comment]
When I was looking at #46 I looked at the `chromium` package's news and found the announcement had a number of other bug listings as part of the removal reasoning, so I wanted to link that announcement here: https://tracker.debian.org/news/1201057/chromium-removed-from-testing/
