### ISSUE TITLE
Install docker, docker-compose, and pip

### ISSUE THREAD

**Issue by KyleEvers** [cisagov/ansible-role-kali#6]
# 🚀 Feature Proposal

Install the following:

- [ ] Docker
- [ ] Docker-compose
- [ ] pip for python2
- [ ] pip for python3

## Motivation

Docker and docker-compose are needed to run the Pentest Portal.

Pip to install tool dependencies. 

## Example
```bash
pip2 install -r requirements.txt
```
## Pitch

These packages are need to run the Pentest Portal as well as install tool requirements. Installing them during the ansible provisioning process seems like the logical place. 

## Notes
We are currently installing the newest version of Docker-compose, version 1.25.4, manually as the version installed by apt-get is not compatible with the Pentest Portal. 

We know python2/pip2 if EOF, but some tools have not made the switch yet.

**Comment by jsf9k** [comment]
Fixed via cisagov/kali-packer#12 and cisagov/ansible-role-docker#13.
