### ISSUE TITLE
Add more tools to Kali image

### ISSUE THREAD

**Issue by jsf9k** [cisagov/ansible-role-kali#8]
# 🚀 Feature Proposal #

The assessment folks have requested more tools be added to the Kali image.  The requested tools are:
- [x] aquatone
- [x] CACTUSTORCH
- [x] checkpwnedemails
- [x] demiguise
- [x] dns-profile-randomizer-master
- [x] docker
- [x] docker-compose
- [x] Empire
- [x] ghostpack
- [x] gnmap-parser
- [x] Gobuster
- [x] Internal-Monologue
- [x] kerberoast
- [x] mikto
- [x] mimikatz
- [x] misc
- [x] mitm6
- [x] morphHTA
- [x] MS17-010
- [x] Neo4J
- [x] nlzr
- [x] nikto
- [x] pip
- [x] PowerSploit
- [x] PowerTools
- [x] PowerUpSql
- [x] RandomPS-Scripts
- [x] Responder
- [x] SecLists
- [x] SessionGopher
- [x] SharpShooter
- [x] Sublist3r
- [x] TikiTorch
- [x] Veil

## Motivation ##

The assessment folks need these tools to perform their assessments.

**Comment by jsf9k** [comment]
The following tools are already installed in the Kali image:
* docker
* docker-compose
* Empire
* Neo4J
* pip
* PowerSploit
* Responder
* SecLists
* Veil

All but docker-compose are installed as Kali packages.

**Comment by jsf9k** [comment]
Lots of tools added in #9.

**Comment by jsf9k** [comment]
Questions I have about specific tools:
* Regarding the tool "ghostpack", do you want all the tools listed [here](https://github.com/GhostPack)?  Those repos appear to be C# code.  Do you intend to compile and run this code in Linux?  If so I need to make sure you have all the tools at hand to do that (mono, for example).
* The tool "Internal-Monologue" [appears to be C# code with a prebuilt Windows EXE and DLL](https://github.com/eladshamir/Internal-Monologue).  Do you intend to compile and run this code in Linux?  If so I want to make sure you have all the tools at hand to do that (mono, for example).
* Regarding the tool "misc", there are [a lot of GitHub repos with that name](https://github.com/search?q=misc).  Can you point me to the one that you want installed?
* Regarding the tool "mitm6", is [this](https://github.com/fox-it/mitm6) the repo you are looking for?
* Regarding the tool "MS17-010", there are [a lot of GitHub repos that could fulfill this requirement](https://github.com/search?q=ms17-010).  Can you point me to the one that you want installed?
* Regarding the tool "scoper", there are [a lot of GitHub repos with that name](https://github.com/search?q=scoper).  Can you point me to the one that you want installed?

**Comment by jsf9k** [comment]
Regarding the tool "mitm6", is [this](https://github.com/fox-it/mitm6) the repo you are looking for?

**Comment by KyleEvers** [comment]
1. Yes, we want all of the Ghostpack tools. The workflow for these libraries is they are normally compiled on a windows machine, then after being compiled they are injected into memory on a victim computer from the kali machine\cobalt strike. A mechanism to have them all pre-compiled on the Kali would be the ideal goal, but just having the repo would be a start. 
2. Same workflow listed above for Ghostpack. 
3. Here is the misc repo in question: [Misc](https://github.com/xan7r/Misc)
4. Yes, that is the correct repo for [mitm6](https://github.com/fox-it/mitm6)
5. Here is the "MS17-010" repo in question: [MS17-010](https://github.com/worawit/MS17-010)
6. The Scoper repo currently on the VM image no longer exists. I will get back to you with a substitute. 

Mono is probably a good addition regardless as some operators do use it. 

Let me know if you have anymore questions.

**Comment by jsf9k** [comment]
Thanks @KyleEvers.  I will look into pre-compiling those C# tools on the Kali image via mono.  I may make that a separate PR, though.

**Comment by jsf9k** [comment]
@KyleEvers, any update on a new scoper repo?

Also, I was told to contact Miguel about the dns-profile-randomizer-master repo.  I reached out to him via trio but have not heard back.  Can you put in a word for me?  Where does that tool live?

**Comment by jsf9k** [comment]
I haven't heard anything about a new repo for the scoper tool, so I am removing it from the list.

**Comment by jsf9k** [comment]
Created #10 for adding `dns-profile-randomizer` to the Kali image.

**Comment by jsf9k** [comment]
There is still a bit more work to do.

**Comment by jsf9k** [comment]
`dns-profile-randomizer` to be added via cisagov/ansible-role-kali#13 and cisagov/kali-packer#26.

**Comment by jsf9k** [comment]
`dns-profile-randomizer` added, which completes the work for this ticket.
